name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"
          cache: true

      - name: Install dependencies
        run: make install-deps

      - name: Format check
        run: make fmt

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Build Docker image (test build only)
        run: make docker # This will build the image locally but not push
